pipeline {
  agent {
    docker {
      image 'maven:3.8.6-eclipse-temurin-11' // Fixed the double username typo
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://18.234.67.228:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "bharani301085/ultimate-cicd:${BUILD_NUMBER}"
      }
      steps {
        script {
            sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
            
            // Using the Docker Pipeline plugin syntax correctly
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }
      }
    }
  } // Added this to close 'stages'
} // Added this to close 'pipeline'
