pipeline {
    agent none // Do not start a container globally

    options {
        skipDefaultCheckout()
    }

    environment {
        DOCKER_IMAGE = "bharani301085/ultimate-cicd"
        SONAR_URL = "http://18.234.67.228:9000"
    }

    stages {
        stage('Initialize & Checkout') {
            agent any // Run this on the host EC2
            steps {
                cleanWs() 
                checkout scm
            }
        }

        stage('Build and Test') {
            agent {
                docker {
                    image 'maven:3.8.6-eclipse-temurin-11'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                dir('Jenkins-Zero-To-Hero/java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Static Code Analysis') {
            agent {
                docker {
                    image 'maven:3.8.6-eclipse-temurin-11'
                    args '--user root'
                }
            }
            steps {
                dir('Jenkins-Zero-To-Hero/java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_AUTH_TOKEN')]) {
                        sh "mvn sonar:sonar -Dsonar.login=\$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}"
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {
            agent any // Run on host because we need the host's Docker daemon
            steps {
                script {
                    dir('Jenkins-Zero-To-Hero/java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                        sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
                        
                        docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                            sh "docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}"
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            node(null) { // Ensure post runs on host
                sh "docker rmi ${DOCKER_IMAGE}:${BUILD_NUMBER} || true"
            }
        }
    }
}
